lab02/encuesta/urls.py
from django.urls import path
from . import views

app_name = 'encuesta'

urlpatterns = [
    # ex: /encuesta/
    path('', views.index, name='index'),
    path('enviar', views.enviar, name = 'enviar'),
    path('calcular/', views.calcular, name='calcular'),
    path('calcular_cilindro/', views.calcular_cilindro, name='calcular_cilindro'),
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuesta/', include ('encuesta.urls')),
    path('admin/', admin.site.urls),
   
]

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/encuesta/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    context = {
        'titulo': "Formulario",
    }
    return render(request, 'encuesta/formulario.html', context)
def enviar(request):
    context = {
        'titulo': "Respuesta",
        'nombre': request.POST['nombre'],
        'clave': request.POST['password'],
        'educacion': request.POST['educacion'],
        'nacionalidad': request.POST['nacionalidad'],
        'idiomas': request.POST.getlist('idiomas'),
        'correo': request.POST['email'],
        'website': request.POST['sitioweb'],
    }
    return render(request, 'encuesta/respuesta.html', context)
def calcular(request):
    if request.method == 'POST':
        num1 = float(request.POST.get('num1'))
        num2 = float(request.POST.get('num2'))
        operacion = request.POST.get('operacion')

        if operacion == 'suma':
            resultado = num1 + num2
            operacion_text = 'suma'
        elif operacion == 'resta':
            resultado = num1 - num2
            operacion_text = 'resta'
        elif operacion == 'multiplicacion':
            resultado = num1 * num2
            operacion_text = 'multiplicación'
        else:
            resultado = 0
            operacion_text = 'operación no válida'

        resultado_text = f'El resultado de {num1} {operacion_text} {num2} = {resultado}'
        return HttpResponse(resultado_text)

    return render(request, 'encuesta/calculadora.html')
def calcular_cilindro(request):
    if request.method == 'POST':
        # Obtener los valores de altura y diámetro del formulario
        altura = float(request.POST['altura'])
        diametro = float(request.POST['diametro'])

        # Calcular el volumen del cilindro (fórmula: π * radio^2 * altura)
        radio = diametro / 2
        volumen = 3.14159265359 * (radio ** 2) * altura

        return render(request, 'encuesta/cilindro_resultado.html', {'volumen': volumen, 'altura': altura, 'diametro': diametro})

    return render(request, 'encuesta/cilindro.html')

lab02/encuesta/templates/encuesta/calculadora.html
<!DOCTYPE html>
<html>
<head>
    <title>Tarea-parte1</title>
</head>
<body>
    <h2>Tarea</h2>
    <form method="post">
        {% csrf_token %}
        <label for="num1">Valor 1:</label>
        <input type="number" name="num1" required><br>

        <label for="num2">Valor 2:</label>
        <input type="number" name="num2" required><br>

        <label for="operacion">Operación:</label>
        <select name="operacion" required>
            <option value="suma">Suma</option>
            <option value="resta">Resta</option>
            <option value="multiplicacion">Multiplicación</option>
        </select><br>

        <input type="submit" value="Calcular">
    </form>
</body>
</html>

lab02/encuesta/templates/encuesta/cilindro.html
<!DOCTYPE html>
<html>
<head>
    <title>Tarea2</title>
</head>
<body>
    <h2>Tarea-parte2</h2>
    <form method="post">
        {% csrf_token %}
        <label for="diametro">Introduzca el Diámetro en Metros:</label>
        <input type="number" name="diametro" step="0.01" required><br>

        <label for="altura">Introduzca la Altura en Metros:</label>
        <input type="number" name="altura" step="0.01" required><br>

        <input type="submit" value="Calcular">
    </form>
</body>
</html>

lab02/encuesta/templates/encuesta/cilindro_resultado.html
<!DOCTYPE html>
<html>
<head>
    <title>Resultado del Cálculo del Volumen</title>
</head>
<body>
    <h2>Resultado del Cálculo del Volumen</h2>
    <p>Introduzca el Diámetro en Metros: {{ diametro }}</p>
    <p>Introduzca la Altura en Metros: {{ altura }}</p>
    <p>El Volumen del Cilindro es: {{ volumen }} metros cúbicos</p>
    <p><a href="{% url 'encuesta:calcular_cilindro' %}">Vuelva a realizar otra operacion</a></p>
</body>
</html>

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>

    Contraseña:
    <input type="password" name="password"><br>

    Educación:
    <select name="educacion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="educacion-obligatoria" selected="selected">Educación Obligatoria</option>
        <option value="formacion-profesional">Formación profesional</option>
        <option value="universidad">Universidad</option>
    </select><br>

    Nacionalidad:
    <input type="radio" name="nacionalidad" value="hispana">Hispana
    <input type="radio" name="nacionalidad" value="otra">Otra<br>

    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked="checked">Español
    <input type="checkbox" name="idiomas" value="inglés">Inglés
    <input type="checkbox" name="idiomas" value="francés">Francés
    <input type="checkbox" name="idiomas" value="aleman">Alemán<br>

    Email:
    <input type="text" name="email"><br>

    Sitio Web:
    <input type="text" name="sitioweb"><br>

    <!-- Botón de enviar -->
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }}</h2>
<p>Nombre: {{ nombre }}</p>
<p>Clave: {{ clave }}</p>
<p>Educación: {{ educacion }}</p>
<p>Nacionalidad: {{ nacionalidad }}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
<p>Email: {{ correo }}</p>
<p>Sitio Web: {{ website }}</p>